### ISSUE TITLE
Model checkpoint links are invalid

### ISSUE THREAD

**Issue by YinpeiDai** [NLPlab-skku/DSTC10_SIMMC2.0#1]
Hi,  can you check whether the trained model parameter links are valid? Thank you!

**Comment by bambidz** [comment]
I opened new links for the parameters.

image_classifiers:
https://drive.google.com/file/d/10vTLbFlYK54CO88EFh3ncNrHkOSGGdG5/view?usp=sharing, 
subtask1:
https://drive.google.com/file/d/15vBI-sbheC9o9A99MhWFyxN9F38IIxuS/view?usp=sharing, 
subtask2-4:
https://drive.google.com/file/d/1g-P_eyJ-x5vEBncNBugTzLn8IEo5ZwVq/view?usp=sharing

**Comment by YinpeiDai** [comment]
Thanks a lot!
